<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-30T18:22:35 IST" name="Default suite" finished-at="2023-09-30T18:22:43 IST" duration-ms="7551">
    <groups>
    </groups>
    <test started-at="2023-09-30T18:22:35 IST" name="Default test" finished-at="2023-09-30T18:22:43 IST" duration-ms="7551">
      <class name="com.qa.test.suit.TC_NewCutomer">
        <test-method signature="verifyWhetherTheMangerAbleToAddNewCustomer()[pri:0, instance:com.qa.test.suit.TC_NewCutomer@b2f4ece]" started-at="2023-09-30T18:22:35 IST" name="verifyWhetherTheMangerAbleToAddNewCustomer" finished-at="2023-09-30T18:22:42 IST" duration-ms="7238" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Not able to Click on New Customer]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Not able to Click on New Customer
at org.testng.Assert.fail(Assert.java:97)
at com.qa.test.reusableComponents.CommonMethods.click_custom(CommonMethods.java:107)
at com.qa.test.pageobject.NewCustomer.clickToNewCutomerTab(NewCustomer.java:57)
at com.qa.test.suit.TC_NewCutomer.verifyWhetherTheMangerAbleToAddNewCustomer(TC_NewCutomer.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWhetherTheMangerAbleToAddNewCustomer -->
      </class> <!-- com.qa.test.suit.TC_NewCutomer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
